In [7]:
import numpy as np

In [3]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [4]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [5]:
import pands as pd

ModuleNotFoundError: No module named 'pands'

In [6]:
import pandas as pd

In [9]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [10]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d[0:2,:2]

array([[ 5, 10],
       [20, 25]])

In [23]:
arr=np.arange(11)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
1/arr

/home/mathan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [27]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [28]:
np.max(arr)

10

In [29]:
np.min(arr)

0

In [30]:
np.maxarg(arr)

AttributeError: module 'numpy' has no attribute 'maxarg'

In [32]:
maxarg.arr()

NameError: name 'maxarg' is not defined

In [33]:
arr.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [34]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [35]:
np.log(arr)


/home/mathan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [36]:
np.remainder(arr)

ValueError: invalid number of arguments

In [37]:
np.add(arr)

ValueError: invalid number of arguments

In [1]:
pythons version of excel is pandas

SyntaxError: invalid syntax (<ipython-input-1-d0bcd65a0544>, line 1)

In [8]:
import pandas as pd

In [3]:
#series

In [4]:
#data_frames

In [5]:
#missing data

In [6]:
#group by

In [7]:
#merging joining concatinating

In [8]:
#oprations

In [9]:
#data input & output

In [13]:
#*******series**********#

In [9]:
lables = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d= {'a':10,'b':20,'c':30}

In [10]:
pd.Series(my_data,index=lables)


a    10
b    20
c    30
dtype: int64

In [11]:

pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [25]:
#series can hold any data type say it be numbers ints boolean 
#functions etc

In [12]:
ser1=pd.Series([1,2,3,4],['usa','germany','ussr','japan'])

In [13]:
ser1

usa        1
germany    2
ussr       3
japan      4
dtype: int64

In [28]:
ser2= pd.Series([1,2,5,4],['usa','germany','italy','japan'])

In [29]:
ser2

usa        1
germany    2
italy      5
japan      4
dtype: int64

In [30]:
ser1['usa']

1

In [31]:
ser2['germany']

2

In [32]:
ser2['japan']

4

In [33]:
ser2[4]

IndexError: index out of bounds

In [34]:
ser3=pd.Series(data=lables)

In [35]:
ser3

0    a
1    b
2    c
dtype: object

In [36]:
ser3[1]

'b'

In [37]:
ser1+ser2

germany    4.0
italy      NaN
japan      8.0
usa        2.0
ussr       NaN
dtype: float64

In [38]:
#int are to be converted to float to avoid data loss 

In [39]:
#pandas and numpy both convert to float

In [40]:
#********data frames*********#

In [41]:
#this is one of the main tool in pandas

In [15]:
from numpy.random import randn

In [16]:
np.random.seed(101)

In [17]:
df = pd.DataFrame(randn(5,4),['A','B','c','D','E'],['W','X','Y','Z'] )

In [18]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [56]:
df['W']

A    0.386030
B    0.681209
c   -1.005187
D   -1.382920
E    0.992573
Name: W, dtype: float64

In [57]:
type(df['W'])

pandas.core.series.Series

In [58]:
type(df)

pandas.core.frame.DataFrame

In [65]:
#done use . method like (df.W) because there maybe lots of methods in this name and it can be
#overriden and cause error so avoid useing functional call 
#use [square brackets instead] that will be a better way 

In [66]:
df[['W','X']]

W         X
A  0.386030  2.084019
B  0.681209  1.035125
c -1.005187 -0.741790
D -1.382920  1.482495
E  0.992573  1.192241

In [71]:
df['new'] =  df['W']+df['Y']

In [72]:
df

W         X         Y         Z       new
A  0.386030  2.084019 -0.376519  0.230336  0.009512
B  0.681209  1.035125 -0.031160  1.939932  0.650049
c -1.005187 -0.741790  0.187125 -0.732845 -0.818062
D -1.382920  1.482495  0.961458 -2.141212 -0.421462
E  0.992573  1.192241 -1.046780  1.292765 -0.054206

In [75]:
df.drop('new',axis = 1,inplace = True) #without inplace data is not delete in df

In [76]:
df

W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
c -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [77]:
df

W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
c -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [78]:
df.drop('E')

W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
c -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212

In [79]:
df.shape

(5, 4)

In [80]:
df

W         X         Y         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
c -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [83]:
df[['Y','Z']]

Y         Z
A -0.376519  0.230336
B -0.031160  1.939932
c  0.187125 -0.732845
D  0.961458 -2.141212
E -1.046780  1.292765

In [85]:
df.loc['A'] #way 1

W    0.386030
X    2.084019
Y   -0.376519
Z    0.230336
Name: A, dtype: float64

In [87]:
df.iloc[2] #way 2

W   -1.005187
X   -0.741790
Y    0.187125
Z   -0.732845
Name: c, dtype: float64

In [88]:
#selsecting subsets in rows and columns

In [90]:
df.loc['B','Y']

-0.031160481493099617

In [93]:
df.loc[['A','B'],['W','Z']]

W         Z
A  0.386030  0.230336
B  0.681209  1.939932

In [2]:
#create new column based on the old columns using arithmetics
#drop a column permanently by using inplace = True also note that axis to be mentioned 
#loc and i loc can be used for indexing purpose or selscting the subsets
#axis = 1 for columns and axis = 0 for rows

In [3]:
#conditional selection and multiindexing

In [19]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
booldf = df > 0

In [22]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df[df>0] #method 2

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
df['W'] > 0

A     True
B     True
c    False
D     True
E     True
Name: W, dtype: bool

In [43]:
df[df['Y']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [46]:
boolser = df ['W'] > 0
result = df [boolser]
mycols = ['Y','X']
result[mycols]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [49]:
df[df['W']>0][['Y','X']] #another method

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [48]:
#multiple conditions